src/AccessControl.Web/Controllers/AccessPointController.cs
using System.Diagnostics.Contracts;
using System.Threading.Tasks;
using System.Web.Mvc;
using AccessControl.Contracts.Commands.Lists;
using AccessControl.Contracts.Commands.Management;
using AccessControl.Contracts.Dto;
using AccessControl.Contracts.Impl.Commands;
using AccessControl.Contracts.Impl.Dto;
using AccessControl.Web.Models.AccessPoint;
using MassTransit;

namespace AccessControl.Web.Controllers
{
    [Authorize]
    public class AccessPointController : Controller
    {
        private readonly IRequestClient<IListAccessPoints, IListAccessPointsResult> _listAccessPointsRequest;
        private readonly IRequestClient<IListDepartments, IListDepartmentsResult> _listDepartmentsRequest;
        private readonly IRequestClient<IRegisterAccessPoint, IVoidResult> _registerAccessPointRequest;

        public AccessPointController(IRequestClient<IListAccessPoints, IListAccessPointsResult> listAccessPointsRequest,
                                     IRequestClient<IListDepartments, IListDepartmentsResult> listDepartmentsRequest,
                                     IRequestClient<IRegisterAccessPoint, IVoidResult> registerAccessPointRequest)
        {
            Contract.Requires(listAccessPointsRequest != null);
            Contract.Requires(listDepartmentsRequest != null);
            Contract.Requires(registerAccessPointRequest != null);

            _listAccessPointsRequest = listAccessPointsRequest;
            _listDepartmentsRequest = listDepartmentsRequest;
            _registerAccessPointRequest = registerAccessPointRequest;
        }

        public async Task<ActionResult> Index()
        {
            var model = new AccessPointIndexViewModel {Editor = new EditAccessPointViewModel()};
            await Initialize(model);
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Index(AccessPointIndexViewModel model)
        {
            if (!ModelState.IsValid)
            {
                await Initialize(model);
                return View(model);
            }

            var accessPoint = new AccessPoint(model.Editor.AccessPointId, model.Editor.Department, model.Editor.Name) {Description = model.Editor.Description};
            var result = await _registerAccessPointRequest.Request(new RegisterAccessPoint(accessPoint));
            if (!result.Succeded)
            {
                ModelState.AddModelError(string.Empty, result.Fault.Summary);
                return View(model);
            }

            return RedirectToAction("Index");
        }

        private async Task Initialize(AccessPointIndexViewModel model)
        {
            var accessPointsTask = _listAccessPointsRequest.Request(ListCommand.WithoutParameters);
            var departmentsTask = _listDepartmentsRequest.Request(ListCommand.WithoutParameters);

            await Task.WhenAll(accessPointsTask, departmentsTask);

            model.AccessPoints = accessPointsTask.Result.AccessPoints;
            model.Editor.AvailableDepartments = departmentsTask.Result.Departments;
        }
    }
}

src/AccessControl.Web/Controllers/BiometricController.cs
using System.Diagnostics.Contracts;
using System.Threading.Tasks;
using System.Web.Mvc;
using AccessControl.Contracts.Commands.Lists;
using AccessControl.Contracts.Commands.Management;
using AccessControl.Contracts.Dto;
using AccessControl.Contracts.Impl.Commands;
using MassTransit;

namespace AccessControl.Web.Controllers
{
    [Authorize]
    public class BiometricController : Controller
    {
        private readonly IRequestClient<IListUsersBiometric, IListUsersBiometricResult> _listUsersRequest;
        private readonly IRequestClient<IUpdateUserBiometric, IVoidResult> _updateBiometricRequest;

        public BiometricController(IRequestClient<IListUsersBiometric, IListUsersBiometricResult> listUsersRequest,
                                   IRequestClient<IUpdateUserBiometric, IVoidResult> updateBiometricRequest)
        {
            Contract.Requires(listUsersRequest != null);
            Contract.Requires(updateBiometricRequest != null);

            _listUsersRequest = listUsersRequest;
            _updateBiometricRequest = updateBiometricRequest;
        }

        // GET: Biometric
        public async Task<ActionResult> Index()
        {
            var result = await _listUsersRequest.Request(ListCommand.WithoutParameters);
            return View(result.Users);
        }

        [HttpPost]
        public async Task<JsonResult> UserHash(string userName, string hash)
        {
            var result = await _updateBiometricRequest.Request(new UpdateUserBiometric(userName, hash));
            return Json(result);
        }
    }
}

src/AccessControl.Web/Controllers/DelegateController.cs
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AccessControl.Contracts.Commands.Lists;
using AccessControl.Contracts.Commands.Management;
using AccessControl.Contracts.Dto;
using AccessControl.Contracts.Impl.Commands;
using AccessControl.Web.Models.Delegate;
using MassTransit;

namespace AccessControl.Web.Controllers
{
    [Authorize]
    public class DelegateController : Controller
    {
        private readonly IRequestClient<IGrantManagementRights, IVoidResult> _grantRequest;
        private readonly IRequestClient<IListDelegatedUsers, IListDelegatedUsersResult> _listDelegatedUsersRequest;
        private readonly IRequestClient<IListUsers, IListUsersResult> _listUsersRequest;
        private readonly IRequestClient<IRevokeManagementRights, IVoidResult> _revokeRequest;

        public DelegateController(IRequestClient<IListUsers, IListUsersResult> listUsersRequest,
                                  IRequestClient<IListDelegatedUsers, IListDelegatedUsersResult> listDelegatedUsersRequest,
                                  IRequestClient<IGrantManagementRights, IVoidResult> grantRequest,
                                  IRequestClient<IRevokeManagementRights, IVoidResult> revokeRequest)
        {
            Contract.Requires(listUsersRequest != null);
            Contract.Requires(listDelegatedUsersRequest != null);
            Contract.Requires(grantRequest != null);
            Contract.Requires(revokeRequest != null);

            _listUsersRequest = listUsersRequest;
            _listDelegatedUsersRequest = listDelegatedUsersRequest;
            _grantRequest = grantRequest;
            _revokeRequest = revokeRequest;
        }

        [HttpPost]
        public async Task<JsonResult> Grant(string userName)
        {
            var result = await _grantRequest.Request(new GrantRevokeManagementRights(userName));
            return !result.Succeded
                       ? Json(new {Succeded = false, result.Fault}, JsonRequestBehavior.AllowGet)
                       : Json(new {Succeded = true}, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Index()
        {
            var listUsersTask = _listUsersRequest.Request(ListCommand.WithoutParameters);
            var listDelegatedTask = _listDelegatedUsersRequest.Request(ListCommand.WithoutParameters);

            await Task.WhenAll(listUsersTask, listDelegatedTask);

            var delegated = new HashSet<string>(listDelegatedTask.Result.UserNames);
            var model = new IndexViewModel
            {
                Users = listUsersTask.Result.Users
                                     .Select(x => new UserViewModel {User = x, IsDelegated = delegated.Contains(x.UserName)})
                                     .ToArray()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<JsonResult> Revoke(string userName)
        {
            var result = await _revokeRequest.Request(new GrantRevokeManagementRights(userName));
            return !result.Succeded
                       ? Json(new {Succeded = false, result.Fault}, JsonRequestBehavior.AllowGet)
                       : Json(new {Succeded = true}, JsonRequestBehavior.AllowGet);
        }
    }
}

src/AccessControl.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AccessControl.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return !User.Identity.IsAuthenticated ? View("Description") : View("Dashboard");
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

src/AccessControl.Web/Controllers/LogController.cs
using System;
using System.Diagnostics.Contracts;
using System.Globalization;
using System.Threading.Tasks;
using System.Web.Mvc;
using AccessControl.Contracts.Commands.Lists;
using AccessControl.Contracts.Impl.Commands;
using AccessControl.Web.Models.Logs;
using MassTransit;

namespace AccessControl.Web.Controllers
{
    [Authorize]
    public class LogController : Controller
    {
        private readonly IRequestClient<IListLogs, IListLogsResult> _listLogsRequest;

        /// <summary>
        ///     Initializes a new instance of the <see cref="LogController" /> class.
        /// </summary>
        /// <param name="listLogsRequest">The list logs request.</param>
        public LogController(IRequestClient<IListLogs, IListLogsResult> listLogsRequest)
        {
            Contract.Requires(listLogsRequest != null);
            _listLogsRequest = listLogsRequest;
        }

        public ActionResult Index()
        {
            var now = DateTime.Now;
            var model = new IndexViewModel
            {
                FromDate = new DateTime(now.Year, now.Month, 1, 0, 0, 0).ToString(CultureInfo.InvariantCulture),
                ToDate = new DateTime(now.Year, now.Month, now.Day, 23, 59, 59).ToString(CultureInfo.InvariantCulture)
            };
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Index(IndexViewModel model)
        {
            DateTime start;
            DateTime end;

            if (!DateTime.TryParse(model.FromDate, CultureInfo.InvariantCulture, DateTimeStyles.AssumeLocal | DateTimeStyles.AdjustToUniversal, out start))
            {
                ModelState.AddModelError("FromDate", "Invalid From date");
            }

            if (!DateTime.TryParse(model.ToDate, CultureInfo.InvariantCulture, DateTimeStyles.AssumeLocal | DateTimeStyles.AdjustToUniversal, out end))
            {
                ModelState.AddModelError("ToDate", "Invalid To date");
            }

            if (start >= end)
            {
                ModelState.AddModelError("FromDate", "From date should less than To date");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var command = ListCommand.ListLogs(start, end);
            var logsResult = await _listLogsRequest.Request(command);
            model.Logs = logsResult.Logs;
            return View(model);
        }
    }
}

src/AccessControl.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>This application was created by Evgeny Shmanev according to requirements of Crossover's CA test task.</p>

src/AccessControl.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Russia, St.Petersburg<br />
    Evgeny Shmanev<br />
    <strong>Phone</strong>: <a href="tel:+7 9500-333-222">+7 9500-333-222</a><br/>
    <strong>email</strong>: <a href="mailto:eshmanev@gmail.com">eshmanev@gmail.com</a><br />
    <strong>www</strong>: <a target="_blank" href="http://evriqum.ru">http://evriqum.ru</a>
</address>

src/AccessControl.Web/Views/Home/Dashboard.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <div class="row">
        <div class="col-md-4 text-center">
            <a href="@Url.Action("Index", "AccessPoint")">
                <p>
                    <img src="@Url.Content("~/Content/access-point.png")" />
                </p>
                Manage access points
            </a>
        </div>
        <div class="col-md-4 text-center">
            <a href="@Url.Action("Index", "AccessRights")">
                <p>
                    <img src="@Url.Content("~/Content/accept-access.png")" />
                </p>
                Allow or Deny access
            </a>
        </div>
        <div class="col-md-4 text-center">
            <a href="@Url.Action("Index", "Biometric")">
                <p>
                    <img src="@Url.Content("~/Content/users.png")" />
                </p>
                Manage biometric data
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 text-center">
            <a href="@Url.Action("Index", "Log")">
                <p>
                    <img src="@Url.Content("~/Content/log.png")" />
                </p>
                View logs
            </a>
        </div>
        <div class="col-md-4 text-center">
            <a href="@Url.Action("Index", "Delegate")">
                <p>
                    <img src="@Url.Content("~/Content/managers.png")"/>
                </p>
                Delegate your rights
            </a>
        </div>
        <div class="col-md-4 text-center">
            
        </div>
    </div>
</div>

src/AccessControl.Web/Views/Home/Description.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ACA system</h1>
    <p class="lead">Access Control and Attendance system manages access control for your manufacturing facilities.</p>
    <p>
        @Html.ActionLink("Click here to login", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", @class= "btn btn-primary btn-lg" })
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

src/AccessControl.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>