src/AccessControl.Web/Models/AccessRights/AccessRightsIndexViewModel.cs
using System;
using System.Linq;
using AccessControl.Contracts.Dto;

namespace AccessControl.Web.Models.AccessRights
{
    public class AccessRightsIndexViewModel
    {
        public IUserAccessRights[] UserAccessRights { get; set; }

        public IUserGroupAccessRights[] UserGroupAccessRights { get; set; }

        public EditAccessRightsViewModel Editor { get; set; }

        public string GetDisplayUserName(string userName)
        {
            var user = Editor.Users.FirstOrDefault(x => x.UserName == userName);
            return user != null ? user.DisplayName : userName;
        }

        public string GetDisplayGroupName(string groupName)
        {
            var group = Editor.UserGroups.FirstOrDefault(x => x.Name == groupName);
            return group != null ? group.DisplayName : groupName;
        }

        public string GetDepartment(Guid accessPointId)
        {
            var accessPoint = Editor.AccessPoints.FirstOrDefault(x => x.AccessPointId == accessPointId);
            return accessPoint != null ? accessPoint.Department : "Unknown department";
        }

        public string GetName(Guid accessPointId)
        {
            var accessPoint = Editor.AccessPoints.FirstOrDefault(x => x.AccessPointId == accessPointId);
            return accessPoint != null ? accessPoint.Name : "Unknown access point";
        }
    }
}

src/AccessControl.Web/Models/AccessRights/EditAccessRightsViewModel.cs
using System;
using System.Collections.Generic;
using AccessControl.Contracts.Dto;

namespace AccessControl.Web.Models.AccessRights
{
    public class EditAccessRightsViewModel
    {
        /// <summary>
        ///     Gets or sets an array of access points.
        /// </summary>
        public IAccessPoint[] AccessPoints { get; set; }

        /// <summary>
        ///     Gets or sets an array of users.
        /// </summary>
        public IUser[] Users { get; set; }

        /// <summary>
        ///     Gets or sets an array of user groups.
        /// </summary>
        public IUserGroup[] UserGroups { get; set; }

        /// <summary>
        ///     Gets or sets an identifier of the selected access point.
        /// </summary>
        public Guid AccessPointId { get; set; }

        /// <summary>
        ///     Gets or sets a name of the selected user.
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        ///     Gets or sets a name of the selected user group.
        /// </summary>
        public string UserGroupName { get; set; }

        /// <summary>
        ///     Gets or sets a value indicating whether a schedule is applied.
        /// </summary>
        /// <value>
        ///     <c>true</c> if schedule is applied; otherwise, <c>false</c>.
        /// </value>
        public bool ScheduleApplied { get; set; }

        /// <summary>
        ///     Gets or sets the time range per days.
        /// </summary>
        /// <value>
        ///     The time range per days.
        /// </value>
        public Dictionary<string, TimeRange> TimeRangePerDays { get; set; }

        /// <summary>
        ///     Gets or sets the scheduler timezone.
        /// </summary>
        /// <value>
        ///     The scheduler timezone.
        /// </value>
        public string SchedulerTimeZone { get; set; }
    }
}

src/AccessControl.Web/Models/AccessRights/TimeRange.cs
using System;

namespace AccessControl.Web.Models.AccessRights
{
    public class TimeRange
    {
        /// <summary>
        /// Gets or sets from time.
        /// </summary>
        /// <value>
        /// From time.
        /// </value>
        public TimeSpan FromTime { get; set; }

        /// <summary>
        /// Gets or sets to time.
        /// </summary>
        /// <value>
        /// To time.
        /// </value>
        public TimeSpan ToTime { get; set; }
    }
}

src/AccessControl.Web/Controllers/AccessRightsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AccessControl.Contracts.Commands.Lists;
using AccessControl.Contracts.Dto;
using AccessControl.Contracts.Impl.Commands;
using AccessControl.Contracts.Impl.Dto;
using AccessControl.Web.Models.AccessRights;
using AccessControl.Web.Services;
using MassTransit;
using TimeRange = AccessControl.Web.Models.AccessRights.TimeRange;

namespace AccessControl.Web.Controllers
{
    [Authorize]
    public class AccessRightsController : Controller
    {
        private readonly IRequestClient<IListAccessPoints, IListAccessPointsResult> _listAccessPointsRequest;
        private readonly IRequestClient<IListAccessRights, IListAccessRightsResult> _listAccessRightsRequest;
        private readonly IRequestClient<IListUserGroups, IListUserGroupsResult> _listUserGroupsRequest;
        private readonly IAccessRightsService _accessRightsService;
        private readonly IRequestClient<IListUsers, IListUsersResult> _listUsersRequest;

        public AccessRightsController(IRequestClient<IListAccessRights, IListAccessRightsResult> listAccessRightsRequest,
                                      IRequestClient<IListAccessPoints, IListAccessPointsResult> listAccessPointsRequest,
                                      IRequestClient<IListUsers, IListUsersResult> listUsersRequest,
                                      IRequestClient<IListUserGroups, IListUserGroupsResult> listUserGroupsRequest,
                                      IAccessRightsService accessRightsService)
        {
            Contract.Requires(listAccessRightsRequest != null);
            Contract.Requires(listAccessPointsRequest != null);
            Contract.Requires(listUsersRequest != null);
            Contract.Requires(listUserGroupsRequest != null);
            Contract.Requires(accessRightsService != null);

            _listAccessRightsRequest = listAccessRightsRequest;
            _listAccessPointsRequest = listAccessPointsRequest;
            _listUsersRequest = listUsersRequest;
            _listUserGroupsRequest = listUserGroupsRequest;
            _accessRightsService = accessRightsService;
        }

        [HttpPost]
        [ActionName("Index")]
        public async Task<ActionResult> Allow(AccessRightsIndexViewModel model)
        {
            if (!ModelState.IsValid)
            {
                await Initialize(model);
                return View(model);
            }

            IVoidResult result = null;
            if (model.Editor.ScheduleApplied)
            {
                if (TimeZoneInfo.FindSystemTimeZoneById(model.Editor.SchedulerTimeZone) == null)
                {
                    ModelState.AddModelError("Editor_SchedulerTimeZone", "Invalid time zone");
                }

                if (ModelState.IsValid)
                {
                    result = await ScheduleAccess(model.Editor);
                }
            }
            else
            {
                result = await AllowPermanentAccess(model.Editor);
            }

            if (result != null && !result.Succeded)
            {
                ModelState.AddModelError(string.Empty, result.Fault.Summary);
            }

            if (!ModelState.IsValid)
            {
                await Initialize(model);
                return View(model);
            }

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> DenyPermanent(bool group, string userOrGroupName, Guid accessPointId)
        {
            var result = !group
                             ? await _accessRightsService.DenyUserAccess(userOrGroupName, accessPointId)
                             : await _accessRightsService.DenyGroupAccess(userOrGroupName, accessPointId);

            if (!result.Succeded)
            {
                ModelState.AddModelError(string.Empty, result.Fault.Summary);
                return await Index();
            }

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> DenySchedule(bool group, string userOrGroupName, Guid accessPointId)
        {
            var result = !group
                             ? await _accessRightsService.DenyScheduledUserAccess(userOrGroupName, accessPointId)
                             : await _accessRightsService.DenyScheduledGroupAccess(userOrGroupName, accessPointId);

            if (!result.Succeded)
            {
                ModelState.AddModelError(string.Empty, result.Fault.Summary);
                return await Index();
            }

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Index()
        {
            var model = new AccessRightsIndexViewModel {Editor = new EditAccessRightsViewModel()};
            await Initialize(model);
            return View(model);
        }

        private Task<IVoidResult> AllowPermanentAccess(EditAccessRightsViewModel editor)
        {
            return string.IsNullOrWhiteSpace(editor.UserName)
                       ? _accessRightsService.AllowGroupAccess(editor.UserGroupName, editor.AccessPointId)
                       : _accessRightsService.AllowUserAccess(editor.UserName, editor.AccessPointId);
        }

        private Task<IVoidResult> ScheduleAccess(EditAccessRightsViewModel editor)
        {
            var schedule = new WeeklySchedule(editor.SchedulerTimeZone);
            foreach (var item in editor.TimeRangePerDays)
            {
                DayOfWeek day;
                if (!Enum.TryParse(item.Key, out day))
                {
                    throw new HttpRequestValidationException();
                }

                schedule.DailyTimeRange.Add(day, new Contracts.Impl.Dto.TimeRange(item.Value.FromTime, item.Value.ToTime));
            }

            return string.IsNullOrWhiteSpace(editor.UserName)
                       ? _accessRightsService.AllowScheduledGroupAccess(editor.UserGroupName, editor.AccessPointId, schedule)
                       : _accessRightsService.AllowScheduledUserAccess(editor.UserName, editor.AccessPointId, schedule);
        }

        private async Task Initialize(AccessRightsIndexViewModel model)
        {
            var accessRightsTask = _listAccessRightsRequest.Request(ListCommand.WithoutParameters);
            var usersTask = _listUsersRequest.Request(ListCommand.WithoutParameters);
            var accessPointsTask = _listAccessPointsRequest.Request(ListCommand.WithoutParameters);
            var userGroupsTask = _listUserGroupsRequest.Request(ListCommand.WithoutParameters);

            await Task.WhenAll(accessRightsTask, usersTask, accessPointsTask, userGroupsTask);

            model.UserAccessRights = accessRightsTask.Result.UserAccessRights;
            model.UserGroupAccessRights = accessRightsTask.Result.UserGroupAccessRights;
            model.Editor.AccessPoints = accessPointsTask.Result.AccessPoints;
            model.Editor.Users = usersTask.Result.Users;
            model.Editor.UserGroups = userGroupsTask.Result.Groups;
            model.Editor.SchedulerTimeZone = TimeZoneInfo.Local.Id;
            model.Editor.TimeRangePerDays = new Dictionary<string, TimeRange>();
            foreach (DayOfWeek day in Enum.GetValues(typeof(DayOfWeek)))
            {
                model.Editor.TimeRangePerDays[day.ToString()] = new TimeRange {FromTime = new TimeSpan(9, 0, 0), ToTime = new TimeSpan(18, 0, 0)};
            }
        }
    }
}

src/AccessControl.Web/Views/AccessRights/EditorPartial.cshtml
@using AccessControl.Web.Models.Validation
@model AccessControl.Web.Models.AccessRights.AccessRightsIndexViewModel

@using (Html.BeginForm("Index", "AccessRights", new { ViewBag.ReturnUrl }, FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "The following errors found", new { @class = "text-danger" })

    <div id="accessRightsEditor" class="panel panel-default">
        <div class="panel-heading"><h4>Allow access to user/group</h4></div>
        <div class="panel-body row">
            <div class="col-sm-4">
                <label class="control-label">Access Point:</label>
                @Html.DropDownListFor(x => x.Editor.AccessPointId, new SelectList(Model.Editor.AccessPoints.OrderBy(x => x.Name), "AccessPointId", "Name"), RequiredSelect.Empty, new {@class = "form-control"})
                @Html.ValidationMessageFor(m => m.Editor.AccessPointId, "", new {@class = "text-danger"})
            </div>

            <div class="col-sm-4">
                <label class="control-label">User:</label>
                @Html.DropDownListFor(x => x.Editor.UserName, new SelectList(Model.Editor.Users.OrderBy(x => x.UserName), "UserName", "DisplayName"), RequiredSelect.Empty, new {@class = "form-control"})
                @Html.ValidationMessageFor(m => m.Editor.UserName, "", new {@class = "text-danger"})
            </div>

            <div class="col-sm-4">
                <label class="control-label">User Group:</label>
                @Html.DropDownListFor(x => x.Editor.UserGroupName, new SelectList(Model.Editor.UserGroups.OrderBy(x => x.Name), "Name", "DisplayName"), RequiredSelect.Empty, new {@class = "form-control"})
                @Html.ValidationMessageFor(m => m.Editor.UserGroupName, "", new {@class = "text-danger"})
            </div>
        </div>
        @Html.HiddenFor(x => x.Editor.ScheduleApplied, new { @id = "scheduleApplied" })
        <table id="schedule" class="table hidden">
            <tr>
                <td colspan="3">
                    <label class="control-label">Time Zone:</label>
                    @Html.DropDownListFor(x => x.Editor.SchedulerTimeZone, new SelectList(TimeZoneInfo.GetSystemTimeZones(), "Id", "DisplayName"), new { @class = "form-control" })
                </td>
            </tr>
            @foreach (var day in Enum.GetValues(typeof(DayOfWeek)).Cast<DayOfWeek>().Select(x => x.ToString()))
            {
                <tr>
                    <td width="50%"><label>@day</label></td>
                    <td>
                        <div class="input-group time" style="width: 200px">
                            @Html.TextBoxFor(x => x.Editor.TimeRangePerDays[day].FromTime, new {@class = "form-control"})
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-time"></span>
                            </span>
                        </div>
                        @Html.ValidationMessageFor(x => x.Editor.TimeRangePerDays[day].FromTime, "", new { @class = "text-danger" })
                    </td>
                    <td>
                        <div class="input-group time" style="width: 200px">
                            @Html.TextBoxFor(x => x.Editor.TimeRangePerDays[day].ToTime, new {@class = "form-control"})
                            <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-time"></span>
                                </span>
                        </div>
                        @Html.ValidationMessageFor(x => x.Editor.TimeRangePerDays[day].ToTime, "", new { @class = "text-danger" })
                    </td>
                </tr>
            }
        </table>
        <div class="panel-footer">
            <button class="btn btn-primary">Apply</button>
            <button id="toggleSchedule" class="btn btn-default">Show schedule</button>
        </div>
    </div>
}

src/AccessControl.Web/Views/AccessRights/Index.cshtml
@model AccessControl.Web.Models.AccessRights.AccessRightsIndexViewModel


<h3>Users' access rights</h3>
<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th rowspan="2">User</th>
            <th colspan="3">Access Rights</th>
            <th rowspan="2">#</th>
        </tr>
        <tr>
            <th>Type</th>
            <th>Department</th>
            <th>Access Point</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var rights in Model.UserAccessRights.OrderBy(x => x.UserName))
        {
            var rowspan = 1;
            if (rights.PermanentAccessRules.Length > 0)
            {
                rowspan += rights.PermanentAccessRules.Length;
            }

            if (rights.ScheduledAccessRules.Length > 0)
            {
                rowspan += rights.ScheduledAccessRules.Length*2;
            }

            <tr><td rowspan="@rowspan">@Model.GetDisplayUserName(rights.UserName)</td></tr>
            @Html.Partial("PermanentPartial", new
            {
                Owner = Model,
                PermanentAccessRules = rights.PermanentAccessRules,
                ScheduledAccessRules = rights.ScheduledAccessRules,
                UserOrGroupName = rights.UserName,
                IsGroup = false
            })
        }
    </tbody>
</table>
<br/>

<h3>User groups' access rights</h3>
<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th rowspan="2">User group</th>
            <th colspan="3">Access Rights</th>
            <th rowspan="2">#</th>
        </tr>
        <tr>
            <th>Type</th>
            <th>Department</th>
            <th>Access Point</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var rights in Model.UserGroupAccessRights)
        {
            var rowspan = 1;
            if (rights.PermanentAccessRules.Length > 0)
            {
                rowspan += rights.PermanentAccessRules.Length;
            }

            if (rights.ScheduledAccessRules.Length > 0)
            {
                rowspan += rights.ScheduledAccessRules.Length*2;
            }

            <tr><td rowspan="@rowspan">@Model.GetDisplayGroupName(rights.UserGroupName)</td></tr>
            @Html.Partial("PermanentPartial", new
            {
                Owner = Model,
                PermanentAccessRules = rights.PermanentAccessRules,
                ScheduledAccessRules = rights.ScheduledAccessRules,
                UserOrGroupName = rights.UserGroupName,
                IsGroup = true
            })
        }
    </tbody>
</table>
<br/>

@Html.Partial("EditorPartial")

@section scripts
{
    <script type="text/javascript" src="~/Scripts/access-rights-index.js"></script>
}

src/AccessControl.Web/Views/AccessRights/PermanentPartial.cshtml
@model dynamic

@foreach (var item in Model.PermanentAccessRules)
{
    <tr>
        <td>Permanent Access</td>
        <td>@Model.Owner.GetDepartment(item.AccessPointId)</td>
        <td>@Model.Owner.GetName(item.AccessPointId)</td>
        <td>@Html.ActionLink("deny", "DenyPermanent", new { accessPointId = item.AccessPointId, userOrGroupName = Model.UserOrGroupName, group = Model.IsGroup })</td>
    </tr>
}

@foreach (var item in Model.ScheduledAccessRules)
{
    <tr>
        <td rowspan="2">Weekly schedule</td>
        <td>@Model.Owner.GetDepartment(item.AccessPointId)</td>
        <td>@Model.Owner.GetName(item.AccessPointId)</td>
        <td rowspan="2">@Html.ActionLink("deny", "DenySchedule", new {accessPointId = item.AccessPointId, userOrGroupName = Model.UserOrGroupName, group = Model.IsGroup})</td>
    </tr>
    <tr>
        <td colspan="2" class="schedule-summary">
            @{
                var zone = TimeZoneInfo.FindSystemTimeZoneById(item.WeeklySchedule.TimeZone);
                var sign = zone.BaseUtcOffset.Hours > 0 ? "+" : "-";
                <div>
                    <label>Time zone</label>
                    <span>(UTC @sign @zone.BaseUtcOffset.ToString("hh\\:mm"))</span>
                </div>
                foreach (var entry in item.WeeklySchedule.DailyTimeRange)
                {
                    <div>
                        <label>@entry.Key</label>
                        <span>@entry.Value.FromTime.ToString("hh\\:mm") - @entry.Value.ToTime.ToString("hh\\:mm")</span>
                    </div>
                }
            }
        </td>
    </tr>
}

src/AccessControl.Web/Views/AccessRights/ScheduledPartial.cshtml
@using AccessControl.Web.Models.AccessRights
@model dynamic

@if (Model.Rules.Length > 0)
{
    foreach (var item in Model.Rules)
    {
        <tr>
            <td rowspan="2">Weekly schedule</td>
            <td>@Model.Owner.GetDepartment(item.AccessPointId)</td>
            <td>@Model.Owner.GetName(item.AccessPointId)</td>
            <td rowspan="2">@Html.ActionLink("deny", "DenySchedule", new { userOrGroupName = Model.Identity, accessPointId = item.AccessPointId, group = Model.IsGroup })</td>
        </tr>
        <tr>
            <td colspan="2">Test</td>
        </tr>
    }
}